# first building react project, using node base image
FROM kartoza/geoserver:latest

# setting working dir inside container
WORKDIR /opt/geoserver

# copy data to data_dir in geoserver
COPY data /opt/geoserver/data_dir